### PR TITLE
indexserver: remove unused GetRepoRank

### PR DESCRIPTION
**Pull request by keegancsmith**
I think this is our older ranking stuff.

Test Plan: go test

### CODE REVIEW

**Comment by stefanhengl** [comment]
Is that a backward compatible change in the sense of gRPC?

**Comment by keegancsmith** [comment]
I think this is declaring something that is exported on the sourcegraph-frontend's grpc server. IE there is probably a corresponding PR on the sg repo to remove the endpoint. So this is safe. For the server side removal it will also be safe because no one is calling it.

**Comment by stefanhengl** [comment]
I meant backward compatible in this sense 

https://learn.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-7.0#protocol-breaking-changes

**Comment by stefanhengl** [comment]
Anyway, it will probably work ;-)

**Review by stefanhengl — APPROVED** [review]

**Comment by keegancsmith** [comment]
It is backwards incompatible in that sense, but it only really counts if a client is trying to call it.

**Pull request merged**
