### PR TITLE
doc: Add a doc/query_syntax.md page

### PR DESCRIPTION
**Pull request by DylanGriffith**
This just links to the HTML source where there are already example queries. This will help with discovery and linking people to docs where they aren't running a local Zoekt instance.

I considered adding all these examples to a markdown page but the duplication seemed like it would be unhelpful trying to maintain multiple sets of documentation. Ideally we'd be able to have a rendered markdown list of examples as well as having it in the Zoekt web application and this might be possible but I wasn't sure what is an elegant way to do this other than some kind of hackery where we had the web page loading and rendering from the markdown source.

An alternative I considered which seems more logical to me (since it's easier for linking people) is to have the Zoekt homepage just link to the markdown docs and move all the examples into a markdown page.

### CODE REVIEW

**Comment by stefanhengl** [comment]
Personally, I like the examples on the webserver's homepage. I refer to them frequently. I think another option would be to document the syntax in markdown and generate the html which we then include in the template. CI could check whether the generated and checked-in html match.

 https://github.com/russross/blackfriday looks promissing. Looking at our go.sum and the output of `go list -m all` we already have it in our dependencies. I haven't looked at it beyond scanning the README so I don't know how easy it is to keep the current formatting.

**Comment by DylanGriffith** [comment]
> Personally, I like the examples on the webserver's homepage. I refer to them frequently.

Good to know. I wasn't really sure because Sourcegraph and GitLab are both consuming Zoekt as an API only so didn't think people would often be on the homepage. In any case I think it still makes sense as Zoekt is a standalone tool and the Web UI examples make the onboarding experience super quick which I like.

> I think another option would be to document the syntax in markdown and generate the html which we then include in the template. CI could check whether the generated and checked-in html match.
>
> https://github.com/russross/blackfriday looks promissing. Looking at our go.sum and the output of `go list -m all` we already have it in our dependencies. I haven't looked at it beyond scanning the README so I don't know how easy it is to keep the current formatting.

Yeah this seems like a good approach. I wouldn't want this to turn out to be too complicated but I do feel like it would be nice if we can try to have a single place for query syntax docs that is linkable and rendered in the home page.

I'll mark this PR draft for now while I look into whether there is a simple enough way to do that.

**Comment by isker** [comment]
> Personally, I like the examples on the webserver's homepage. I refer to them frequently.

I don't mean to derail the direction of this PR (it sounds good to me), but I would additionally appreciate more authoritative and comprehensive documentation on zoekt query syntax in this project, beyond the relatively simple examples that you can fit into any UI's homepage.

I wrote a little bit about it in my (very WIP) alternative zoekt frontend `neogrok`, all by squinting at the source, experimenting, and making educated guesses: https://neogrok-demo-web.fly.dev/syntax.  Even after writing all that I _still_ don't understand the meaning of or intent behind `type:`, for example, which is why it's not included there.

**Comment by DylanGriffith** [comment]
@stefanhengl I started to look at the idea of extracting the examples into Markdown that could both be rendered in GitHub  and also rendered onto the homepage of Zoekt and it didn't really practically work out. Apart from this being a kinda hacky idea of rendering docs into static HTML at compile time for the webserver, we also have the problem that we want the examples on the home page to actually be links to searches. So we have an example like:

```
<dt><a href="search?q=thread+or+needle">thread or needle</a></dt><dd>search for either "thread" or "needle"</dd>
```

but in the markdown we can't actually have it as a link to `search?q=thread+or+needle` as this would be a link inside GitHub which would not work. So I figured if I could extract this into some kind of data format then I could use that to generate the HTML as well as the docs so I converted all the examples to YAML like:

```yaml
---
- query: needle
  description: search for "needle"
- query: thread or needle
  description: search for either "thread" or "needle"
- query: class needle
  description: 'search for files containing both "class" and "needle"'
- query: class Needle
  description: search for files containing both "class" (case insensitive) and "Needle" (case sensitive)
- query: class Needle case:yes
  description: search for files containing "class" and "Needle", both case sensitively
- query: '"class Needle"'
  description: search for files with the phrase "class Needle"
- query: needle -hay
  description: search for files with the word "needle" but not the word "hay"
- query: path file:java
  description: search for the word "path" in files whose name contains "java"
- query: needle lang:python
  description: search for "needle" in Python source code
- query: f:.c$
  description: search for files whose name ends with ".c"
- query: path -file:java
  description: search for the word "path" excluding files whose name contains "java"
- query: foo.*bar
  description: search for the regular expression "foo.*bar"
- query: "-(Path File) Stream"
  description: search "Stream", but exclude files containing both "Path" and "File"
- query: "-Path file Stream"
  description: search "Stream", but exclude files containing "Path File"
- query: sym:data
  description: ''
- query: phone r:droid
  description: search for "phone" in repositories whose name contains "droid"
- query: phone archived:no
  description: search for "phone" in repositories that are not archived
- query: phone b:master
  description: for Git repos, find "phone" in files in branches whose name contains "master".
- query: phone b:HEAD
  description: for Git repos, find "phone" in the default ('HEAD') branch.
```

But then I felt like this was a weird rabbithole because having the examples in a YAML file committed to the repo doesn't really help with my original goal of having them in a markdown docs page that can be linked to. It would help if we were generating a static website somewhere that hosted the docs for Zoekt but if we just want to rely on the markdown as rendered by GitHub it doesn't really help.

So after all that I'm thinking that the minimum I have here is probably a good starting point so that anybody looking at this project in GitHub at least knows where to go to get an idea of how the query syntax works. Also @isker it's possible that the other examples of keywords you mention being missing could just be even more examples on the homepage.

In general I think probably the most maintainable and comprehensive approach to this kind of documentation would be:

1. Create a comprehensive docs page somewhere (in Markdown on GitHub or a static site generator)
1. Update the homepage of Zoekt to only include a few (maybe 3 simple examples) and then add a link to the bottom of the examples linking to the authoritative source of the query syntax docs

I don't really know if that's going to be universally liked though if people are enjoying the long list of examples on the homepage.

Alternatively I'm happy to take all the examples from the homepage and duplicate them in Markdown here if you think that's a better option than the current state of this PR.

WDYT?

**Comment by stefanhengl** [comment]
@DylanGriffith Thanks for looking into this! Let's go with what you have right now. 

I think an authorative doc/query_syntax.md with a link on the homepage is a good way to go moving forward.

**Review by stefanhengl — APPROVED** [review]

**Comment by KonradStanski** [comment]
Sorry to jump in here, but I have a quick question:
You reference a zoekt HTML homepage. Is there a demo app running somewhere where this can be seen?

**Pull request merged**
