### PR TITLE
all: rely on priority in RawConfig only

### PR DESCRIPTION
**Pull request by keegancsmith**
This allows us to remove maintaining priority.json and loading it in. I believe this simplifies the code quite a bit. We can do this now that we have cheap metadata updates.

### CODE REVIEW

**Review by tsenart — APPROVED** [review]
LGTM, nice!

**Review by rmmh — APPROVED** [review]
This is a good cleanup. Do we have another easy way to ensure that we have priorities for all of our repos?

**Comment by keegancsmith** [comment]
> Do we have another easy way to ensure that we have priorities for all of our repos?

@rmmh We've lost the prometheus gauge. I can add it back, except it won't deal with errors like before. I can make it percentage based. Alternatively we can increment a counter in frontend when we encounter a zero priority that we send to zoekt? Another alternative is a guage in zoekt-webserver over its shard, which will be on what is actually searched.

Taking a step back, do we need a metric for this? It seems like a detail that we can rely on as being correct now? My gut says no. But if you are actively monitoring this, I'll add a metric back. Out of my suggestions above, the one in zoekt-webserver is the one I like the most since it most closely relates to user experience.

**Comment by keegancsmith** [comment]
I'm gonna merge, and can follow-up with a metric if needed.

**Pull request merged**
