### PR TITLE
zoekt-webserver: graceful shutdown on SIGINT and SIGTERM

### PR DESCRIPTION
**Pull request by keegancsmith**
We handle SIGINT and SIGTERM differently. For SIGTERM we wait 15s since
Kubernetes may still be sending traffic. This is an attempt to remove
the "Readiness probe failed" events on Sourcegraph.com when rolling out
a new version of Zoekt.

### CODE REVIEW

**Review by pecigonzalo — APPROVED** [review]
Nice! LGTM but I dont know how to test Zoekt in isolation just to test this signal. 

For reference, I've used https://github.com/ory/graceful (either directly or reference implementation) and https://blog.cloudflare.com/exposing-go-on-the-internet/ as baseline config. If this works well, I think we should make it a lib for all other services (or use an existing library).

**Comment by keegancsmith** [comment]
> Nice! LGTM but I dont know how to test Zoekt in isolation just to test this signal.

I do the following:

``` shell
go mod edit -replace github.com/google/zoekt=$GOPATH/src/github.com/google/zoekt
```

Note: Our dev environment does some funky stuff where we build prom-wrapper/etc in a container using our go.mod. This breaks using local replace directives like above. So I also have setup my environment to exclude those steps / using local binaries instead of docker where possible:

``` shell
export CTAGS_COMMAND=$HOME/src/github.com/universal-ctags/ctags/ctags
export USE_SYNTECT_SERVER_FROM_PATH=t
export SRC_DEV_EXCEPT=grafana,prometheus,postgres_exporter
```

I then tested with `pkill -TERM zoekt-webserver` and `pkill -INT zoekt-webserver`. I tested the scenario with ongoing requests, and sending the signal more than once.

> For reference, I've used https://github.com/ory/graceful (either directly or reference implementation)

Great, I took a look at that. Unfortunetly it doesn't encode the behaviour I am trying to fix. It encourages immiediate graceful shutdown. However, on Kubernetes you need to wait before draining your connection. I found this article an exceptional resource https://learnk8s.io/graceful-shutdown


> and https://blog.cloudflare.com/exposing-go-on-the-internet/ as baseline config.

That looks great. We don't directly expose our go to the internet anywhere luckily enough. We normally are going through an Ingress / nginx of some sort. But I agree, that baseline is great and it wouldn't hurt to just use that anyways.

**Comment by pecigonzalo** [comment]
TIL, I was under the impression that when the pod enters termination lifecycle, ingress stops sending traffic to it like in this comment https://github.com/kubernetes/kubernetes/issues/64510#issuecomment-452295436 and this google article https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace, and that SIGTERM would be sent only after that action and the pod being removed from the service, but it does not seem to be the case, good catch and great article.

**Comment by pecigonzalo** [comment]
Related issue: https://github.com/sourcegraph/sourcegraph/issues/13453

**Pull request merged**
