### PR TITLE
binds the index server on all addresses to allow external access for …

### PR DESCRIPTION
**Pull request by davejrt**
…services such as prometheus

### CODE REVIEW

**Review by daxmc99 — APPROVED** [review]
LGTM

**Comment by daxmc99** [comment]
Someone familiar with the CI here should weight in to see if the container images will automatically update

**Review by uwedeportivo — APPROVED** [review]

**Comment by uwedeportivo** [comment]
yeah, it will build insiders images

**Comment by keegancsmith** [comment]
Currently CI is broken on this repo (have it in my todo list to fix before release) https://github.com/sourcegraph/zoekt/runs/745955493

FYI the images built by this CI are not directly used by sourcegraph. Instead in the sourcegraph repo we retag the image. We fetch the corresponding image in our `go.mod`. You can update that with `./dev/zoekt/update` in the sourcegraph repo. I'll see if I can quickly fix zoekt CI now.

**Comment by keegancsmith** [comment]
The jansson-dev package in alpine removed the static archive, which we included in our build of ctags https://gitlab.alpinelinux.org/alpine/aports/-/commit/569cdb02b4418a574184113b313b5fd89893e8f7#note_94337 This will affect the sourcegraph repo at some point (when we upgrade alpine). For now I am going to workaround it by pinning the version of alpine we build with. Fixed in https://github.com/sourcegraph/zoekt/commit/a20174182c8186f46d441f5df246748df468c49e

Here is the corresponding PR in sourcegraph repo to get the image built https://github.com/sourcegraph/sourcegraph/pull/11335

**Pull request merged**
