### PR TITLE
list: add indextime to MinimalRepoListEntry

### PR DESCRIPTION
**Pull request by keegancsmith**
We want this information in Sourcegraph. This turned into a bit more of a hairy change due to our custom marshalling (for perf) and grpc validation.

I am strongly considering making the type for
MinimalRepoListEntry.IndexTime just an int64 and storing the unix time without milliseconds. This not only changes the struct size from 56 bytes to 40, but likely makes much of the code simpler to reason about.

Test Plan: lots of unit test coverage

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]
LGTM 👍

**Comment by keegancsmith** [comment]
The only real change to end users is we will now start storing timestamps in UTC. This was something we missed before. In practice this is a non change since servers should be running in that tz. Even if not, I don't imagine this breaking anything.

**Comment by keegancsmith** [comment]
> I am strongly considering making the type for
MinimalRepoListEntry.IndexTime just an int64 and storing the unix time without milliseconds. This not only changes the struct size from 56 bytes to 40, but likely makes much of the code simpler to reason about.

@camdencheek thoughts on this point?

**Comment by keegancsmith** [comment]
I am experimenting quick to see how easy the change is. This is the docstring I wrote to motivate as extra info:

```
	// IndexTimeUnixSeconds is the IndexTime converted to unix time. This is to
	// make it clear we are not transporting the full fidelty timestamp (ie with
	// milliseconds and location). Additionally it saves 16 bytes in this
	// struct.
```

**Review by efritz — APPROVED** [review]

**Comment by camdencheek** [comment]
> thoughts on this point?

The only extra we get from a `time.Time` is timezone, monotonicity, and convenience. We don't care about timezone (should always be UTC), we don't care about monotonicity, and convenience is easy to get around by adding a method that returns `IndexTime` as a `time.Time` if needed. 

Using an int64 seems fine to me

**Comment by keegancsmith** [comment]
alright done. will shephard this into main then sourcegraph.

**Pull request merged**
