### PR TITLE
all: remove detailed debug file logging

### PR DESCRIPTION
**Pull request by keegancsmith**
We have noticed profiles where lumberjack is responsible for 1GB of memory. This is surprising and we haven't used the log output in a long time. Rather than debugging, we are going to remove it for now and when we need detailed logs again we can add something back.

Test Plan: go test

### CODE REVIEW

**Review by jtibshirani — APPROVED** [review]
Makes sense to me, in some recent debugging sessions, I didn't find this output to be relevant.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
We ran into this at @gitlab as well ([downstream issue](https://gitlab.com/gitlab-org/gitlab/-/issues/452169)). The underlying problem is the following:

- Lumberjack is configured to write log files to the index directory.
- The index directory contains many files, in our case on the order of 450k files.
- When lumberjack scans the directory for old logs to archive, it needs to scan over all of these files as well when it performs a ReadDir.
- `ioutil.ReadDir` also performs an `os.Lstat`, so we allocate a stat struct for each of these files.
- We also spend roughly 66% of all CPU time on those `lstat` syscalls.

An alternate fix could have been to create a separate log directory, but removing the lumberjack dependency altogether is totally reasonable!

**Comment by keegancsmith** [comment]
@igorwwwwwwwwwwwwwwwwwwww thanks for posting your investigation results. Did you ever look at those logs?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@keegancsmith AFAIK we never did.

**Pull request merged**
