### PR TITLE
zoekt-webserver: remove watchdog

### PR DESCRIPTION
**Pull request by keegancsmith**
We rely on our health endpoint and kubernetes managing the liveness of
the process.

### CODE REVIEW

**Comment by dadlerj** [comment]
One thing to think about is non-K8s deployments. Would this cause problems on Docker Compose?

**Comment by keegancsmith** [comment]
@slimsag do we have healthchecks in docker-compose?

This is our only service in Sourcegraph which has a watchdog, everything else relies on health checks encoded into the  deployment environment

**Comment by emidoots** [comment]
Sure do: https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml#L196

**Comment by keegancsmith** [comment]
Rather than remove watchdog, I've made it configurable. See https://github.com/sourcegraph/sourcegraph/pull/15148

**Pull request closed without merging**
