### PR TITLE
Export prometheus metrics

### PR DESCRIPTION
**Pull request by ijt**
This PR makes `zoekt-webserver` and `zoekt-sourcegraph-webserver` export Prometheus metrics and notify Sentry on 500s, as suggested by Keegan's [comment](https://github.com/sourcegraph/sourcegraph/issues/5243#issuecomment-524032505) about enabling alerts for the indexing pod in Kubernetes deployments.

The package `github.com/sourcegraph/sourcegraph/pkg/trace` has been copied into `pkg/trace` and modified to work with Zoekt. There is some risk that bugs fixed in the original won't be immediately fixed in this fork of the trace package. At the same time, that has to be weighed against the risk of not getting alerts when the the indexing pod is unavailable.

### CODE REVIEW

**Comment by emidoots** [comment]
Haven't reviewed the code yet, but some initial thoughts:

- Can we just use Prometheus directly instead of `pkg/trace`? What tradeoffs exist here?
- If we do need `pkg/trace`, can we just directly import `pkg/trace` from the main repo instead of copying?
- If we set up instrumentation like this, will we be able to extend this to other non-Sourcegraph-owned parts of the codebase? e.g. if we want to add metrics around more core parts of Zoekt, will we be able to do that with this approach?

I suspect what may make more sense for now is using Prometheus directly and adding a small middleware to the Zoekt codebase separately which monitors HTTP status codes.

cc @uwedeportivo since he has looked at how to track this same type of thing (HTTP error rates, latency) in other services in our codebase and may have ideas. Any thoughts?

**Comment by uwedeportivo** [comment]
@ijt @slimsag we already have several middleware packages that do tracing and prom metrics. here's what i found a while ago looking through our source (this list is probably not complete): 

https://github.com/sourcegraph/sourcegraph/issues/5201

not sure if the items there can be applied here or combined into a single way to do http tracing and monitoring. most of the stuff listed in that inventory does it from the client POV, this is from the server POV. i also understand zoekt is special 😄, so this might be the best way.

**Review by keegancsmith — CHANGES_REQUESTED** [review]
Can you just export the prometheus handlers and not copy in our debug/trace in this PR. The extra logging stuff you have here won't do anything because we use `net/rpc` which doesn't propogate span IDs. IE this can be a very simple PR which just adds the handlers for promhttp onto zoekt-webserver and zoekt-sourcegraph-indexserver.

**Comment by ijt** [comment]
Thanks for the review. I have to focus on literal search and Uwe has agreed to set up alerting for the indexed search pod so I'm closing this.

**Pull request closed without merging**
