### PR TITLE
Make IndexGitRepo signal whether there were changes

### LINKED ISSUE #780: gitindex: inform the caller whether there were changes since the last index
We run [this fork](https://github.com/isker/zoekt/commit/e331e40bed8f6bd1014107e4c98e691118059e54) in our indexer, which tells us whether incremental git indexing resulted in any changes.  Knowing whether there were any changes can drive metrics and even help prioritize subsequent indexes (e.g. backoff indexing repos that infrequently change).

That commit as it is would certainly be an unacceptable breaking change, but I'm curious what maintainers' thoughts on this approach are.  Am I missing a better way to do this?  Would a not-breaking overload of `IndexGitRepo` that does something like this be acceptable?

### PR DESCRIPTION
**Pull request by isker**
As described, we'd like this information to be externally available to drive metrics for incremental indexing.

Closes #780.

### CODE REVIEW

**Comment by isker** [comment]
Hmm, I've contributed in the past without signing that.

**Review by keegancsmith — APPROVED** [review]

**Comment by keegancsmith** [comment]
> Hmm, I've contributed in the past without signing that.

I'll be honest I don't know much about these things, let me check in.

**Comment by isker** [comment]
Sorry about those test failures, to be honest I thought `go build ./...` compiled tests.  Should be good now.

**Comment by isker** [comment]
@keegancsmith ping

**Comment by jtibshirani** [comment]
@isker sorry for the slow response!! We require a CLA for Zoekt contributions too. I can merge right after it's signed.

**Comment by isker** [comment]
@jtibshirani Please help me understand. This has not been required for my and others' previous contributions, and it of course was not required for contributions to the project as it existed before sourcegraph took ownership.

The project has in fact already seen a situation like this where the CLA requirement was determined to be a mistake (presumably because it was blanket applied to the sourcegraph org?): https://github.com/sourcegraph/zoekt/pull/409#issuecomment-1216944947. You're saying this is not a mistake this time? cc @jdorfman.

**Comment by jdorfman** [comment]
@isker looking into this now.

**Comment by jdorfman** [comment]
@isker Update: I reached out to legal to understand why your past 7 commits were CLA-free. I will follow up ASAP.

**Comment by isker** [comment]
My past commits were CLA-free because there was no requirement to sign a CLA, and indeed you removed that requirement after it was briefly added for a time: https://github.com/sourcegraph/zoekt/pull/409#issuecomment-1216966870.  It is the same for any other past contributor to the project; it has nothing to do with me in particular.

**Comment by jtibshirani** [comment]
@isker I was mistaken about our policy, I apologize for that! @jdorfman thanks for jumping in here and helping figure this out.

**Comment by isker** [comment]
Thanks. This otherwise just needs somebody to merge 🌞.

**Comment by jdorfman** [comment]
@keegancsmith @jtibshirani, you can override and merge this while I deal with legal. If someone asks you why, you can link back to this very comment. :)

@isker thanks so much for your contribution. I apologize for the unpleasant experience. That's on me.

**Pull request merged**
