### PR TITLE
Expand Repository.MergeMutable to cover more fields

### LINKED ISSUE #683: `Repository.MergeMutable` doesn't handle changes to *Template fields
Hi.  I changed the `CommitURLTemplate` on some (non-git!) repos we are indexing and noted that they did not get reindexed with the new template.  This is because changes to that field (and related ones) are not being handled in `Repository.MergeMutable`:

https://github.com/sourcegraph/zoekt/blob/bec12a772b51bd06a65ca4dd58d0eb348033b313/api.go#L654

@keegancsmith (since you're on blame 🌞) would Sourcegraph be negatively impacted if they were?  Is there any reason to not add these?

### PR DESCRIPTION
**Pull request by isker**
There was no test coverage, so I added some.

Closes #683.

### CODE REVIEW

**Comment by isker** [comment]
I've only handled the few fields that look trivially okay, but MergeMutable might want to handle more:
- `Source` (should be mutable just like `URL`?)
- `priority` (should be mutable? can ignore RawConfig entries named `"priority"`?)
- `Rank` (sounds like it should be mutable)
- `LatestCommitDate` (? but maybe this is redundant with Branches, one should not change without the other)

And I'm not sure about the two Tombstone fields.

Even if some of those should be added, I am also fine to stop with these if you prefer 🌞.

**Review by keegancsmith — COMMENTED** [review]
I confirmed that templates and URL are set before we call anything that goes down this path in everything. However, in the case of sourcegraph's indexserver we don't have those fields set so this will misfire. So can't land this just yet, but that is on us. I will take a look soon.

> * `Source` (should be mutable just like `URL`?)
> * `LatestCommitDate` (? but maybe this is redundant with Branches, one should not change without the other)

These should only change if we reindex content. So should ignore it in this function.

> * `priority` (should be mutable? can ignore RawConfig entries named `"priority"`?)
> * `Rank` (sounds like it should be mutable)

Yeah these indeed are mutable. But I'd need to read some more code to work out if its safe to change, lets keep this PR to just the fields you changed.

> And I'm not sure about the two Tombstone fields.

This you should ignore as well.

**Comment by isker** [comment]
@keegancsmith any update?

**Comment by keegancsmith** [comment]
> @keegancsmith any update?

Apologies mostly away from keyboard this week (team meetup). On my list to tackle for next week.

**Comment by isker** [comment]
@keegancsmith happy new year 😄.

**Comment by isker** [comment]
@keegancsmith I've fixed the merge conflicts that developed on this. Please take a look.

**Comment by keegancsmith** [comment]
So sorry for dropping this. We welcome open source contributions and I've dropped the ball here. Will take a look today.

**Review by keegancsmith — APPROVED** [review]
LGTM. I tested this  a bunch and how it interacts with Sourcegraph. It all just works because in sg we never set URL or template fields. Sorry again about the delays.

**Comment by isker** [comment]
No worries, thanks!

**Pull request merged**
