### PR TITLE
wip: ci: add golang-ci-lint step 

### PR DESCRIPTION
**Pull request by ggilmore**
Following up on https://github.com/sourcegraph/zoekt/pull/214#discussion_r759931063

This PR ATM is just adding the CI step and configuration file - I haven't followed up on the failures it's reporting to see whether or not they're legitimate.

I am also open to tweaking the list of checks that we use (I just stole this config from another repo of mine).

### CODE REVIEW

**Comment by ggilmore** [comment]
One path we could take here (if we agree on the list of checks) is to [disable the linter](https://golangci-lint.run/usage/false-positives/) on the existing lines that it's complaining about. That way we don't have to address each failure as a prerequisite to merging this PR.

**Comment by keegancsmith** [comment]
LGTM. Looks like most of the lints are just style/warnings and not finding real bugs. Either way the list looks fine to me and making us lint clean sounds good to me.

**Comment by keegancsmith** [comment]
I was waiting for zoekt to roll out and got carried away with fixing a bunch of these. Most of these where simple and I just pushed to master. I opened up one or two PRs, once they land then we should be golangci-lint clean

**Comment by tsenart** [comment]
This seems abandoned. Please re-open if not.

**Pull request closed without merging**
